### PR TITLE
Add coverage make target

### PR DESCRIPTION
**Pull request by sjaeckel**
Which runs the tests and creates code coverage using lcov

### CODE REVIEW

**Comment by moxie0** [comment]
Thanks for the PR @sjaeckel. Apologies but we just now got our CLA server setup for this repo, would you mind closing the PR and opening a new one?

**Comment by sjaeckel** [comment]
Sure, NP

**Comment by sjaeckel** [comment]
Thanks.

**Comment by sjaeckel** [comment]
Oh I just realized... the next time please don't edit someones' commit, but just add another commit with your changes :-)

**Comment by dkonigsberg** [comment]
Was unsure how to proceed in that specific case of a relatively minor edit. Noted for future reference.

**Comment by moxie0** [comment]
@sjaeckel That's how we do it here. We want every commit in the repository to represent an ideal state, without any "in progress" or "transitional" commits.  For larger changes we would get back to you and ask you to fix the commit, but we don't always have that much time and will just fix them up for smaller stuff.  Sorry, that's how it's gotta be!

**Pull request closed without merging**
